apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: admin-rpc
  labels:
    app: openshift-rpc-daemon
spec:
  selector:
    matchLabels:
      app: openshift-rpc-daemon
  template:
    metadata:
      labels:
        app: openshift-rpc-daemon
    spec:
      hostPID: true
      containers:
      - name: admin-rpc
        command:
        - /server
        image: @@IMAGE@@
        env:
        ports:
        - name: grpc
          containerPort: 12021
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 256Mi
        volumeMounts:
          # name must match the volume name below
          - name: cert-volume
            mountPath: /etc/admin-rpc/certs/
            readOnly: true
        securityContext:
          privileged: true
      volumes:
      - name: cert-volume
        secret:
          secretName: service-serving-cert
