apiVersion: v1
kind: Service
metadata:
  labels:
    app: openshift-rpc-daemon
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: service-serving-cert
  name: rpc
spec:
  ports:
  - name: grpc
    port: 443
    targetPort: grpc
  selector:
    app: openshift-rpc-daemon
