auth:
  namespace: default
  verb: get
  resource: pods
  version: v1
cmdName: "date"

requiredFlags:
permittedShortFlags:
- u
- R
permittedLongFlags:
  utc:
  universal:
  rfc-3339:
  rfc-email:
permittedNouns:
