auth:
  namespace: default
  verb: get
  resource: pods
  version: v1
cmdName: "docker"
requiredFlags:
permittedShortFlags:
  - a
  - q
permittedLongFlags:
  digests:
  - "^true$"
  - "^false$"
  format:
  - "^.*$"
  filter:
  - "^.*$"
  no-stream:
permittedNouns:
  - version
  - info
  - ps
  - stats
  - images


