auth:
  namespace: default
  verb: get
  resource: pods
  version: v1
cmdName: "ethtool"
requiredFlags:
permittedShortFlags:
- i
permittedLongFlags:
permittedNouns:
- '^eth[[:digit:]]$'
- '^enp[[:xdigit:]]s[[:xdigit:]]+$'
