auth:
  namespace: default
  verb: get
  resource: pods
  version: v1
cmdName: "hostname"
requiredFlags:
permittedShortFlags:
- I
- A
- s
permittedLongFlags:
  all-ip-addresses:
  all-fqdns:
  short:
permittedNouns:
