auth:
  namespace: default
  verb: get
  resource: pods
  version: v1
cmdName: "iptables-save"
requiredFlags:
permittedShortFlags:
  - c
permittedLongFlags:
  counters:
  table:
    - "^[[:alpha:]]+$"
permittedNouns:
