cmdName: "ls"
requiredFlags:
permittedShortFlags:
  - a
  - A
  - b
  - c
  - d
  - f
  - g
  - h
  - H
  - i
  - k
  - l
  - L
  - m
  - n
  - N
  - o
  - Q
  - r
  - R
  - s
  - S
  - t
  - u
  - U
  - v
  - x
  - X
  - Z
  - "1"
permittedLongFlags:
  all:
  almost-all:
  author:
  escape:
  block-size:
    - "^.*$"
  ignore-backups:
  color:
    - "^.*$"
  directory:
  dired:
  classify:
  file-type:
  format:
  full-time:
  group-directories-first:
  no-group:
  human-readable:
  si:
  dereference-command-line:
  dereference-command-line-symlink-to-dir:
  hide:
    - "^.*$"
  indicator-style:
    - "^.*$"
  inode:
  ignore:
    - "^.*$"
  kibibytes:
  dereference:
  numeric-uid-gid:
  literal:
  de-control-chars:
  show-control-chars:
  quote-name:
  quoting-style:
    - "^.*$"
  reverse:
  recursive:
  size:
  sort:
    - "^.*$"
  time:
    - "^.*$"
  time-style:
    - "^.*$"
  tabsize:
    - "^.*$"
  width:
    - "^.*$"
  context:
  help:
  version:
permittedNouns:
- "^.*"
