auth:
  namespace: default
  verb: get
  resource: pods
  version: v1
cmdName: "ovs-ofctl"
requiredFlags:
permittedShortFlags:
  - O
permittedLongFlags:
permittedNouns:
  - dump-flows
  - OpenFlow13
  - OpenFlow14
  - "^br0$"
