auth:
  namespace: default
  verb: get
  resource: pods
  version: v1
cmdName: "pidstat"
requiredFlags:
permittedShortFlags:
  - l
  - w
  - u
  - d
  - r
  - t
  - h
  - p
permittedLongFlags:
permittedNouns:
  - "^[[:digit:]]+$"
  - "^ALL$"

