auth:
  namespace: default
  verb: get
  resource: pods
  version: v1
cmdName: "systemd-cgls"
requiredFlags:
permittedShortFlags:
  - l
  - k
permittedLongFlags:
  all:
  full:
  unit:
    - "^.*$"
  user-unit:
    - "^.*$"
  machine:
    - "^.*$"
permittedNouns:
