auth:
  namespace: default
  verb: get
  resource: pods
  version: v1
cmdName: "uptime"
requiredFlags:
permittedShortFlags:
  - p
  - h
  - s
  - V
permittedLongFlags:
  pretty:
  help:
  since:
  version:
permittedNouns:
