auth:
  namespace: default
  verb: get
  resource: pods
  version: v1
cmdName: "vmstat"
requiredFlags:
permittedShortFlags:
  - w
permittedLongFlags:
permittedNouns:
  # This would be better if we could force 2 digits
  - "^[[:digit:]]+$"
